# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58d68a5e8629825a2ebe9ddea7f1ea29f543d2c056b9f1e27b1d6f385a9605c4128013cbaf5e9f58e07a7d5e840919ce6ec433ee9ac16ad63e246f5c9aa58d1b

test:
  secret_key_base: 1cbb5c1fcfc5061636df18a4babad932b3e3abfd2e10164e4ae180f181451051814660b8274f59c4ee139e24306194b779207e2f242adc05caa58cc5a6a3d024

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
